# Generated by Django 3.0.4 on 2020-03-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('contactor', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_position', models.CharField(max_length=50)),
                ('employee_state', models.CharField(max_length=10)),
                ('start_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_stock',
            fields=[
                ('order_stock_date', models.DateField()),
                ('order_num', models.IntegerField()),
                ('order_stock_po', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_stock_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_number', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order_stock_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_po', models.CharField(max_length=50)),
                ('valid_date', models.DateField()),
                ('product_num', models.IntegerField()),
                ('note', models.CharField(max_length=50, null=True)),
                ('order_detail_status', models.BooleanField(default=False)),
                ('order_stock_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Order_stock')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order_stock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_no', models.CharField(max_length=50)),
                ('pay_way', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=50, null=True)),
                ('ask_date', models.DateField()),
                ('demand_date', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('product_amount', models.IntegerField()),
                ('get_date', models.DateField(null=True)),
                ('expect_date', models.DateField(null=True)),
                ('order_no', models.CharField(max_length=50)),
                ('deliver_way', models.CharField(max_length=50, null=True)),
                ('note1', models.CharField(max_length=50, null=True)),
                ('product_no', models.CharField(max_length=50, null=True)),
                ('invoice_condition', models.BooleanField(default=False)),
                ('actual_ship_date', models.DateField(null=True)),
                ('finished', models.BooleanField(default=False)),
                ('last_modified', models.DateField(auto_now=True)),
                ('charger_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='select_data.Employee')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Customer')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
            ],
        ),
    ]
