# Generated by Django 3.0.4 on 2020-03-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_position', models.CharField(max_length=50)),
                ('employee_state', models.CharField(max_length=10)),
                ('start_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('factory_id', models.AutoField(primary_key=True, serialize=False)),
                ('factory_site', models.CharField(max_length=30)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Order_get',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('get_order_date', models.DateTimeField()),
                ('po_num', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('produced_date', models.DateField()),
                ('num_rest', models.IntegerField()),
                ('now_time', models.DateField(auto_now=True, verbose_name='date of today')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('people_id', models.AutoField(primary_key=True, serialize=False)),
                ('people_name', models.CharField(max_length=30)),
                ('factory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_num', models.IntegerField()),
                ('product_require_date', models.IntegerField()),
                ('other_command', models.CharField(max_length=200)),
                ('expected_ship_date', models.DateTimeField()),
                ('actual_ship_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('custom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Employee')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Order_get')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
                ('reponse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.People')),
            ],
        ),
    ]
