# Generated by Django 3.0.4 on 2020-03-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_get',
            name='po_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
