# Generated by Django 3.0.4 on 2020-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order_stock_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_all_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_stock_detail',
            name='order_stock_detail_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_number',
            field=models.CharField(max_length=50),
        ),
    ]
