# Generated by Django 3.0.4 on 2020-04-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0003_order_stock_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_stock',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='order_stock',
            name='product_number',
        ),
        migrations.CreateModel(
            name='Order_stock_product',
            fields=[
                ('order_stock_product', models.AutoField(primary_key=True, serialize=False)),
                ('order_num', models.IntegerField()),
                ('order_stock_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Order_stock')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
            ],
        ),
    ]
