# Generated by Django 3.0.4 on 2020-04-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0003_auto_20200329_2013'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
