# Generated by Django 3.0.4 on 2020-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0003_auto_20200313_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='now_time',
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='other_command',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
