# Generated by Django 3.0.4 on 2020-03-15 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0004_auto_20200313_2016'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order_detail',
            managers=[
                ('record', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='reponse_id',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='response_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='select_data.Employee'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='custom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.People'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='other_command',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='product_require_date',
            field=models.IntegerField(null=True),
        ),
    ]
