# Generated by Django 3.0.4 on 2020-04-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0004_auto_20200415_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='product_po',
        ),
        migrations.CreateModel(
            name='Order_detail_po',
            fields=[
                ('order_detail_po_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_po', models.CharField(max_length=50)),
                ('product_amount', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Order')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
            ],
        ),
    ]
