# Generated by Django 3.0.4 on 2020-04-05 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0004_auto_20200402_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_no',
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Order')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_data.Product')),
            ],
            managers=[
                ('record', django.db.models.manager.Manager()),
            ],
        ),
    ]
