# Generated by Django 3.0.4 on 2020-04-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0005_auto_20200425_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail_po',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order_detail_po',
            name='order_detail_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='select_data.Order_detail'),
            preserve_default=False,
        ),
    ]
