# Generated by Django 3.0.4 on 2020-03-17 14:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0005_auto_20200315_1648'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock',
            managers=[
                ('record', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='actual_ship_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='other_command',
            field=models.CharField(default='No command', max_length=200),
        ),
        migrations.AlterField(
            model_name='order_get',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_period',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
