# Generated by Django 3.0.4 on 2020-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0006_auto_20200426_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_stock',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
