# Generated by Django 3.0.4 on 2020-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0007_auto_20200317_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
