# Generated by Django 3.0.4 on 2020-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0007_order_stock_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_stock_detail',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
