# Generated by Django 3.0.4 on 2020-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0008_auto_20200317_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_get',
            name='get_order_date',
            field=models.DateField(),
        ),
    ]
