# Generated by Django 3.0.4 on 2020-04-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0008_order_stock_detail_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_stock_detail',
            name='order_stock_po',
        ),
        migrations.AddField(
            model_name='order_stock_detail',
            name='order_stock_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='select_data.Order_stock_product'),
            preserve_default=False,
        ),
    ]
