# Generated by Django 3.0.4 on 2020-04-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0009_auto_20200427_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail_po',
            name='product_number',
        ),
    ]
