# Generated by Django 3.0.4 on 2020-04-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0010_remove_order_detail_po_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_stock_detail',
            name='product_number',
        ),
    ]
