# Generated by Django 3.0.4 on 2020-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0011_remove_order_stock_detail_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
