# Generated by Django 3.0.4 on 2020-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0012_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_stock_product',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
