# Generated by Django 3.0.4 on 2020-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_data', '0013_order_stock_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_state',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
